version: '3.1'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: build
      MYSQL_PASSWORD: build
      MYSQL_DATABASE: airosearch
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mariadb: